// src/components/templates/welcome-screen/welcome-screen.tsx
import { Button } from '../../../components/atoms';
import { FolderOpen } from 'lucide-react';
import { Kbd } from '../../../components/ui/kbd';

interface WelcomeScreenProperties {
	os: 'mac' | 'windows' | 'linux';
	onOpenProject: () => void;
}

export function WelcomeScreen({ os, onOpenProject }: WelcomeScreenProperties) {
	return (
		<div className="bg-background flex min-h-screen flex-col items-center justify-center">
			<div className="space-y-8 text-center">
				<h1 className="text-foreground text-4xl font-bold">
					Welcome to Zinc IDE
				</h1>
				<p className="text-muted-foreground text-lg">
					Start coding with a powerful, functional IDE built for
					developers.
				</p>
				<div className="space-y-4">
					<Button onClick={onOpenProject} size="lg" className="w-48">
						<FolderOpen className="mr-2 h-4 w-4" />
						Open Project
					</Button>
				</div>
				<p className="text-muted-foreground text-sm">
					Tip: Press{' '}
					{os === 'mac' ? (
						<>
							<Kbd>⌘</Kbd> <Kbd>O</Kbd>
						</>
					) : (
						<>
							<Kbd>Ctrl</Kbd> <Kbd>O</Kbd>
						</>
					)}{' '}
					to open a project.
				</p>
			</div>
		</div>
	);
}

// crates/ide/src/lib/components/molecules/WelcomeScreen.svelte
<script lang="ts">
	import { Button } from '$lib/components/atoms';

	interface Props {
		onOpenFolder: () => void;
		onOpenFile: () => void;
		version: string;
	}

	let { onOpenFolder, onOpenFile, version }: Props = $props();
</script>

<div class="flex flex-col items-center justify-center h-screen">
	<div class="text-6xl mb-4">🚀</div>
	<h1 class="text-2xl mb-2">Welcome to Zinc IDE</h1>
	<p class="text-gray-600 mb-4">{version}</p>
	<div class="flex gap-4">
		<Button onclick={onOpenFolder}>Open Folder</Button>
		<Button onclick={onOpenFile}>Open File</Button>
	</div>
	<p class="text-sm text-gray-500 mt-4">Tip: Use Cmd+O to open a folder quickly.</p>
</div>
